version : '2'

services:
  dotnetblrmvcapp:
    build:
      context: ./bdotnet-mvc-demo
    ports:
      - 5000:5000
    depends_on:
      - dotnetblrwebapi
  dotnetblrwebapi:
    build:
      context: ./bdotnet-webapi-demo
    ports:
      - 8000